import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    images: '/jak.png',
  },
};

export default function RootLayout({
  children,
  parallel1,
  parallel2,
}: {
  children: React.ReactNode;
  parallel1: React.ReactNode;
  parallel2: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {parallel1}
        {parallel2}
      </body>
    </html>
  );
}
